version: '3'
services:
  api:
    build: backend
    volumes:
      - type: bind
        source: ./backend
        target: /home/backend
    networks:
      - net
    ports:
      - 3000:3000
    depends_on:
      - database
        #@TODO healthcheck

  database:
    image: mysql
    restart: always
    environment:
      #sEcUrItY
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    networks:
      - net
    ports:
      - 5432:5432
  
networks:
  net:
    driver: bridge