version: '3'
services:
  api:
    build: backend
    volumes:
      - type: bind
        source: ./backend
        target: /home/backend
    networks:
      - net
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - database.env
      #Its not clear from the pdf if i should receive a .env or a arquivo.env file
      #Anyway, I'll cover both
      - .env
      - arquivo.env
    links:
      - database

  database:
    image: mysql
    restart: always
    env_file:
      - database.env
    networks:
      - net
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "mysql -h localhost -u  root -proot" ]
      interval: 3s
      timeout: 5s
      retries: 10
  
networks:
  net:
    driver: bridge